version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/a1.ddvi.io
permissions:
  - object: /
    pattern: "*.js"
    except: [webconfig.js]
  - object: /var/www/a1.ddvi.io/test
    pattern: "**"
    except: [hide.js]
    owner: www-data
hooks:
  BeforeInstall:
    - location: deploy-scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
      - location: deploy-scripts/start_server.sh
        timeout: 300
        runas: root
  ApplicationStop:
    - location: deploy-scripts/stop_server.sh
      timeout: 300
      runas: root